### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by hequano** [yutianqaq/BypassAV-Online#2]
![报错](https://github.com/yutianqaq/BypassAV-Online/assets/108477709/935305b2-102d-4602-bf3b-72ae2db00c97)

**Comment by yutianqaq** [comment]
一般是没有编译器导致的，还没做异常处理。有时间会加一个一键安装，检查环境之类的脚本

**Comment by yutianqaq** [comment]
找到了问题了，c语言的只是测试模板，之后才会增加支持。真正能用的是nim的 x2ldr 模板。压缩包默认密码是yutian

**Comment by furuanruan** [comment]
遇到一样的问题，最后发现是配置文件application.yaml里的路径和本机的不一样，自行修改后正常运行

**Comment by furuanruan** [comment]
落地被火绒秒了。。。

**Comment by yutianqaq** [comment]
> 落地被火绒秒了。。。

下个版本更新

**Comment by hequano** [comment]
> 遇到一样的问题，最后发现是配置文件application.yaml里的路径和本机的不一样，自行修改后正常运行

问题解决，感谢哥们。
